# YML : Jobs Package on GreenOne Project
name: Package

on:
  # Jobs run when 'pull_request' on 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Debug Git
        run: git log

      - name: Run Package 
        shell: powershell
        run: |
            cd "C:\Users\SERV-ADMIN\Desktop\GreenOneProject\"
            .\package_ue5.ps1